{{- $topValues := .Values }}
{{- if $topValues.applicationSpecs }}
{{- $applicationSpecs := $topValues.applicationSpecs }}
{{- $wlSpecs := $topValues.workloadSpecs }}
{{- range $appname, $appData := $applicationSpecs }}
{{if eq $appData.apptype "static-pod" }}
{{- $containers := $appData.containers }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ $.Chart.Name }}-{{ $appname }}
  labels:
    app: {{ $.Chart.Name }}-{{ $appname }}
{{ include "hb.labels.standard" . | indent 4 }}
spec:
  {{- if $appData.restartPolicy }}
  restartPolicy: {{$appData.restartPolicy}}
  {{ end }}
  {{- with $topValues.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $appData.initContainers }}
  initContainers:
  {{- range $appData.initContainers }}
  - {{- toYaml . | nindent 4 }} 
    volumeMounts:
    {{- if $topValues.defaultVolumeMounts }}
    {{- range $mount := $topValues.defaultVolumeMounts }}
      - name: {{ $mount.name }}
        mountPath: {{ $mount.mountPath }}
    {{- end }}
    {{- end }}
    {{- if $appData.volumeMounts }}
      {{- toYaml $appData.volumeMounts |  nindent 6 }}
    {{- end }}
  {{- end }}
  {{- end }}
  containers:
  {{- range $containerName, $container := $containers }}
    - name: {{ $containerName }}
      image: {{ $container.image.repository }}:{{ $container.image.tag }}{{if $container.image.pullPolicy }}
      imagePullPolicy: {{ $container.image.pullPolicy }}{{else if (($topValues.image).pullPolicy) }}
      imagePullPolicy: {{ $topValues.image.pullPolicy }}
      {{- end }}
      {{- if $container.command }}
      command:
        {{- toYaml $container.command |  nindent 8 }}
      {{- end }}
      {{- if $container.args }}
      args:
        {{- toYaml $container.args |  nindent 6 }}
      {{- end }}
      {{- if $container.env }}
      env:
      {{- toYaml $container.env | nindent 6 }}
      {{- end }}
      {{- if $container.readinessProbe  }}
      readinessProbe:
        {{- toYaml $container.readinessProbe | nindent 8 }}
      {{- end }}
      {{- if $container.livenessProbe  }}
      livenessProbe:
        {{- toYaml $container.livenessProbe | nindent 8 }}
      {{- end }}
      {{- $workload_resources := "" }}
      {{- if and ($wlSpecs) ($container.workload) }}
      {{- $workload_resources = index $wlSpecs $container.workload  "wl_resources"  }}
      {{- end }}
      {{- if $workload_resources }}
      #wld resources
      resources:
      {{- toYaml $workload_resources| nindent 8 }}
      {{- else if $container.resources }}
      #cont resources
      resources:
      {{- toYaml $container.resources| nindent 8 }}
      {{- end }}
      volumeMounts:
      {{- if $topValues.defaultVolumeMounts }}
        #Default volumeMounts
      {{- range $mount := $topValues.defaultVolumeMounts }}
        - name: {{ $mount.name }}
          mountPath: {{ $mount.mountPath }}
      {{- end }}
      {{- end }}
      {{- if $container.volumeMounts }}
          #Container volumeMounts
        {{- toYaml $container.volumeMounts |  nindent 8 }}
      {{- end }}
      {{- if $container.ports }}
      ports:
        {{- toYaml $container.ports | nindent 8 }}
      {{- end }}
  {{- end }}
  {{- with $appData.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $appData.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $appData.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  volumes:
  {{- if $appData.volumes }}
      #App Volumes
    {{- toYaml $appData.volumes |  nindent 4 }}
  {{- end }}
  {{- if $topValues.defaultVolumes }}
      #Default Volumes
  {{- range $vol := $topValues.defaultVolumes }}
    - {{ toYaml $vol | nindent 6 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}