{{- $topValues := .Values }}
{{- if $topValues.applicationSpecs }}
{{- $applicationSpecs := $topValues.applicationSpecs }}
{{- range $appname, $appData := $applicationSpecs }}
{{if and (eq $appData.apptype "cronjob") ($appData.schedule) }}
{{- $containers := $appData.containers }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $.Chart.Name }}-{{ $appname }}
  labels:
    app: {{ $.Chart.Name }}-{{ $appname }}
{{ include "hb.labels.standard" . | indent 4 }}
spec:
  schedule: {{$appData.schedule}}
  {{- if $appData.extraSpecs }}
  {{- $appData.extraSpecs | toYaml | nindent 2}}
  {{- end }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- with $topValues.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
          {{- $appData.podSecurityContext | default $topValues.podSecurityContext | toYaml | nindent 12 }}
          restartPolicy: {{$appData.restartPolicy | default "OnFailure"}}
          {{- with $appData.initContainers }}
          initContainers:
          {{- range $appData.initContainers }}
          - {{- toYaml . | nindent 12 }} 
            volumeMounts:
            {{- if $topValues.defaultVolumeMounts }}
            {{- range $mount := $topValues.defaultVolumeMounts }}
              - name: {{ $mount.name }}
                mountPath: {{ $mount.mountPath }}
                subPath: {{ $mount.subPath }}
            {{- end }}
            {{- end }}
            {{- if $appData.volumeMounts }}
              {{- toYaml $appData.volumeMounts |  nindent 14 }}
            {{- end }}
            {{- if .resources }}
              #cont resources
            resources:
            {{- toYaml ( mergeOverwrite .resources ( default dict $topValues.resources ) ) | nindent 14 }}
            {{- else if $topValues.resources }}
            resources:
            {{- toYaml $topValues.resources | nindent 14 }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- if $appData.dnsPolicy }}
          dnsPolicy: {{ $appData.dnsPolicy }}
          {{- end }}
          containers:
      {{- range $containerName, $container := $containers }}
          - name: {{ $containerName }}
            image: {{ $container.image.repository }}:{{ $container.image.tag }}{{if $container.image.pullPolicy }}
            imagePullPolicy: {{ $container.image.pullPolicy }}{{else if (($topValues.image).pullPolicy) }}
            imagePullPolicy: {{ $topValues.image.pullPolicy }}
            {{- end }}
            {{- if $container.command }}
            command:
              {{- toYaml $container.command |  nindent 12 }}
            {{- end }}
            {{- if $container.args }}
            args:
              {{- toYaml $container.args |  nindent 10 }}
            {{- end }}
            {{- if $container.env }}
            env:
            {{- toYaml $container.env | nindent 10 }}
            {{- end }}
            securityContext:
            {{- $container.securityContext | default $topValues.securityContext  | toYaml | nindent 14 }}
            {{- if $container.resources }}
            #cont resources
            resources:
            {{- toYaml ( mergeOverwrite $container.resources ( default dict $topValues.resources ) ) | nindent 14 }}
            {{- else if $topValues.resources }}
            resources:
            {{- toYaml $topValues.resources | nindent 14 }}
            {{- end }}
            volumeMounts:
            {{- if $topValues.defaultVolumeMounts }}
              #Default volumeMounts
            {{- range $mount := $topValues.defaultVolumeMounts }}
              - name: {{ $mount.name }}
                mountPath: {{ $mount.mountPath }}
                subPath: {{ $mount.subPath }}
            {{- end }}
            {{- end }}
            {{- if $container.volumeMounts }}
              #Container volumeMounts
              {{- toYaml $container.volumeMounts |  nindent 12 }}
            {{- end }}
          {{- with $appData.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with $appData.affinity }}
          affinity:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with $appData.tolerations }}
          tolerations:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          volumes:
          {{- if $appData.volumes }}
            #App Volumes
            {{- toYaml $appData.volumes |  nindent 14 }}
          {{- end }}
          {{- if $topValues.defaultVolumes }}
            #Default Volumes
          {{- range $vol := $topValues.defaultVolumes }}
            - {{ toYaml $vol | nindent 14 }}
          {{- end }}
          {{- end }}
       {{- end }}

{{- end }}
{{- end }}
{{- end }}
