{{- $topValues := .Values }}
{{- with $topValues.serviceAccessCredentials}}
{{- $svcCreds := . }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $.Chart.Name }}-{{$svcCreds.name}}
data:
  {{- $creds := $svcCreds.credentials }}
  {{- range $key, $value := $creds }}
  {{$key}}: {{$value | b64enc }}
  {{- end }}
{{- end }}