{{- $topValues := .Values }}
{{- if $topValues.applicationSpecs }}
{{- $applicationSpecs := $topValues.applicationSpecs }}
{{- range $appname, $appData := $applicationSpecs }}
{{if eq $appData.apptype "statefull" }}
{{- $containers := $appData.containers }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Chart.Name }}-{{ $appname }}
spec:
  serviceName: {{ $.Chart.Name }}-{{ $appname }}
  {{- if $appData.replicas }}
  replicas: {{ $appData.replicas }}
  {{- else if $topValues.replicas }}
  replicas: {{ $topValues.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}-{{ $appname }}
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}-{{ $appname }}
    spec:
      {{- with $topValues.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $appData.initContainers }}
      initContainers:
      {{- range $appData.initContainers }}
      - {{- toYaml . | nindent 8 }} 
        volumeMounts:
        {{- if $topValues.defaultVolumeMounts }}
        {{- range $mount := $topValues.defaultVolumeMounts }}
          - name: {{ $mount.name }}
            mountPath: {{ $mount.mountPath }}
        {{- end }}
        {{- end }}
      {{- if $appData.volumeMounts }}
        {{- toYaml $appData.volumeMounts |  nindent 10 }}
      {{- end }} # range
      {{- end }} #if
      {{- end }}
      containers:
      {{- range $containerName, $container := $containers }}
      - name: {{ $containerName }}
        image: {{ $container.image.repository}}:{{ $container.image.tag }}
        {{- if $container.command }}
        command:
          {{- toYaml $container.command |  nindent 10 }}
        {{- end }}
        {{- if $container.args }}
        args:
          {{- toYaml $container.args |  nindent 10 }}
        {{- end }}
        {{- if $container.env }}
        env:
          {{- toYaml $container.env |  nindent 10 }}
        {{- end }}
        {{- if $container.ports }}
        ports:
        {{- toYaml $container.ports | nindent 10 }}
        {{- end }}
        {{- if $container.resources }}
        resources:
          {{- toYaml $container.resources| nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- if $topValues.defaultVolumeMounts }}
        {{- range $mount := $topValues.defaultVolumeMounts }}
          - name: {{ $mount.name }}
            mountPath: {{ $mount.mountPath }}
        {{- end }}
        {{- end }}
        {{- if $container.volumeMounts }}
          # Container Volume mount
          {{- toYaml $container.volumeMounts |  nindent 10 }}
        {{- end }}
      {{- end }}
      volumes:
      {{- if $appData.volumes }}
        {{- toYaml $appData.volumes |  nindent 6 }}
      {{- end }}
      {{- if $topValues.defaultVolumes }}
      {{- range $vol := $topValues.defaultVolumes }}
      {{- if ( hasKey $vol "createPv" ) }}
      {{- if $vol.createPv }}
        - name: {{ $vol.name }}
          persistentVolumeClaim:
            claimName: {{ $.Chart.Name }}-{{ $vol.name }}-pvc
      {{- end }}
      {{- else }}
        - {{ toYaml $vol | nindent 10 }}
      {{- end }}
      {{- end }}
      {{- end }}
  {{- if $appData.volumeClaimTemplates }}
  volumeClaimTemplates:
  {{- range $vct := $appData.volumeClaimTemplates}}
  - {{- toYaml $vct |  nindent 5 }} 
  {{- end }}
  {{- end }}
---

{{- end }}
{{- end }}
{{- end }}