{{- $topValues := .Values }}
{{- if $topValues.applicationSpecs }}
{{- $applicationSpecs := $topValues.applicationSpecs }}
{{- range $appname, $appData := $applicationSpecs }}
{{if eq $appData.apptype "job" }}
{{- $containers := $appData.containers }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Chart.Name }}-{{ $appname }}
  labels:
    app: {{ $.Chart.Name }}-{{ $appname }}
{{ include "hb.labels.standard" . | indent 4 }}
spec:
  {{- if $appData.jobOptions }}
    {{- $appData.jobOptions | toYaml | nindent 2 }}
  {{- end }}
  {{- if $appData.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{$appData.activeDeadlineSeconds}}
  {{- end }}
  template:
    spec:
      {{- with $appData.initContainers }}
      initContainers:
      {{- range $appData.initContainers }}
      - {{- toYaml . | nindent 8 }} 
        volumeMounts:
        {{- if $topValues.defaultVolumeMounts }}
        {{- range $mount := $topValues.defaultVolumeMounts }}
        - name: {{ $mount.name }}
          mountPath: {{ $mount.mountPath }}
        {{- end }}
        {{- end }}
        {{- if $appData.volumeMounts }}
          {{- toYaml $appData.volumeMounts |  nindent 10 }}
        {{- end }}
      {{- end }}
      {{- end }}
      restartPolicy: {{$appData.restartPolicy | default "Never"}}
      securityContext:
      {{- $appData.podSecurityContext | default $topValues.podSecurityContext | toYaml | nindent 8 }}
      {{- with $topValues.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
  {{- range $containerName, $container := $containers }}
      - name: {{ $containerName }}
        image: {{ $container.image.repository }}:{{ $container.image.tag }}{{if $container.image.pullPolicy }}
        imagePullPolicy: {{ $container.image.pullPolicy }}{{else if (($topValues.image).pullPolicy) }}
        imagePullPolicy: {{ $topValues.image.pullPolicy }}
        {{- end }}
        {{- if $container.command }}
        command:
          {{- toYaml $container.command |  nindent 12 }}
        {{- end }}
        {{- if $container.args }}
        args:
          {{- toYaml $container.args |  nindent 10 }}
        {{- end }}
        {{- if $container.env }}
        env:
        {{- toYaml $container.env | nindent 10 }}
        {{- end }}
        securityContext:
        {{- $container.securityContext | default $topValues.securityContext  | toYaml | nindent 12 }}
        {{- if $container.resources }}
        #cont resources
        resources:
        {{- toYaml $container.resources| nindent 12 }}
        {{- end }}
        volumeMounts:
        {{- if $topValues.defaultVolumeMounts }}
          #Default volumeMounts
        {{- range $mount := $topValues.defaultVolumeMounts }}
          - name: {{ $mount.name }}
            mountPath: {{ $mount.mountPath }}
        {{- end }}
        {{- end }}
        {{- if $container.volumeMounts }}
          #Container volumeMounts
          {{- toYaml $container.volumeMounts |  nindent 12 }}
        {{- end }}
      {{- with $appData.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with $appData.affinity }}
      affinity:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with $appData.tolerations }}
      tolerations:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      volumes:
      {{- if $appData.volumes }}
        #App Volumes
        {{- toYaml $appData.volumes |  nindent 12 }}
      {{- end }}
      {{- if $topValues.defaultVolumes }}
        #Default Volumes
      {{- range $vol := $topValues.defaultVolumes }}
        - {{ toYaml $vol | nindent 14 }}
      {{- end }}
      {{- end }}
  {{- end }}

{{- end }}
{{- end }}
{{- end }}