{{- $topValues := .Values }}
{{- if $topValues.logging }}
{{- if $topValues.logging.enable }}
{{- if eq $topValues.logging.enable true }}
{{- if $topValues.applicationSpecs }}
{{- $applicationSpecs := $topValues.applicationSpecs }}
{{- range $appname, $appData := $applicationSpecs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Chart.Name }}-{{ $appname }}-kratos-fluent-bit-config
  labels:
{{ include "hb.labels.standard" . | indent 4 }}
{{- include "std-helm.labels" $ | nindent 4 }}
data:
  logrotate-fluentbit.conf: |
    {{ range $container := $appData.containers }}
    {{- if $container.logging }}
    {{- if $container.logging.logFileInfo }}
    {{- range $lfi := $container.logging.logFileInfo }}
    {{- range $f := $lfi.files }}
      {{ $f }} {
          rotate 3
          hourly
          copytruncate
          missingok
          size 100M
      }
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}

  fluent-bit.conf: |
    {{ range $container := $appData.containers }}
    {{- if $container.logging }}
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        {{- if $container.logging.fluentBitParserConfigFiles }}
        {{- range $f := $container.logging.fluentBitParserConfigFiles }}
        Parsers_File  {{ $f }}
        {{- end }}
        {{- end }}
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE filter-kubernetes.conf
    {{- if $topValues.logging.nSpectId }}
    @INCLUDE nspect.conf
    {{- end }}
    @INCLUDE k8s-metadata.conf
    {{- if $container.logging.fluentBitCustomIncludes }}
    {{- range $f := $container.logging.fluentBitCustomIncludes }}
    @INCLUDE {{ $f }}
    {{- end }}
    {{- end }}
    @INCLUDE output-lumberjack.conf
    {{ end }}
    {{ end }}

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

  nspect.conf: |
    [FILTER]
        Name modify
        Match *
        {{- if $topValues.logging.nSpectId }}
        Add nspectid {{ $topValues.logging.nSpectId }}
        {{- end }}

  k8s-metadata.conf: |
    [FILTER]
        Name modify
        Match *
        Add node_name ${NODE_NAME}
        Add namespace ${POD_NAMESPACE}
        Add pod_name ${POD_NAME}
        Add pod_ip ${POD_IP}

  output-lumberjack.conf: |
    [OUTPUT]
        Name            lumberjack
        Match           *
        Retry_Limit     False
        host_out        ${FLUENT_LUMBERJACK_HOST}
        host_port       ${FLUENT_LUMBERJACK_PORT}
        event_extras    {"fields": {"topic": "{{ $topValues.logging.topic }}"}}
        ssl             On
        ssl.crt_file    /fluent-bit/certs/client_chain.crt
        ssl.key_file    /fluent-bit/certs/client.key
        timeout         500

{{- end}}
{{- end}}
{{- end}}
{{- end}}
{{- end}}
