{{- $topValues := .Values }}
{{- with $topValues.serviceAccessCredentials}}
{{- $svcCreds := . }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{$svcCreds.name}}
  labels:
{{ include "hb.labels.standard" . | indent 4 }}
{{- include "std-helm.labels" $ | nindent 4 }}
data:
  {{- $creds := $svcCreds.credentials }}
  {{- range $key, $value := $creds }}
  {{$key}}: {{$value | b64enc }}
  {{- end }}
{{- end }}