{{- $topValues := .Values }}
{{- if $topValues.ingress }}
{{- if $topValues.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Chart.Name }}-ingress
  labels:
{{ include "hb.labels.standard" . | indent 4 }}
{{- include "std-helm.labels" $ | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{.Values.ingress.className | default "nginx" }}
    {{- with .Values.ingress.annotations}}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if $topValues.ingress.extraSpecs }}
  {{- $topValues.ingress.extraSpecs | toYaml | nindent 2}}
  {{- end }}
  rules:
  {{- with .Values.ingress.rules}}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}
{{ end }}
