dependencies:
- name: etcd
  version: 6.3.3
  repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
  condition: etcd.enabled
  tags:
    - etcd
- name: minio
  version: 8.0.14
  repository: https://milvus-io.github.io/milvus-helm
  condition: minio.enabled
  tags:
    - minio
